// ── 自动生成（AOT 算子融合），请勿手动编辑 ──
// 表达式: rope_forward_dk64
#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Buf0 { float b0[]; };
layout(std430, binding = 1) readonly buffer Buf1 { float b1[]; };
layout(std430, binding = 2) readonly buffer Buf2 { float b2[]; };
layout(std430, binding = 3) readonly buffer Buf3 { float b3[]; };
layout(std430, binding = 4) writeonly buffer BufOut { float bout[]; };

layout(push_constant) uniform PC {
    uint count;
    uint cols;
};

void main()
{
    const uint i = gl_GlobalInvocationID.x;
    if (i >= count) return;
    const uint row = i / cols;
    const uint col = i % cols;
    const float v0 = b0[i];
    const float v1 = (((row % 64u) < 32u) ? -b1[(((row / 64u) * 64u + (row % 64u) + 32u) * cols + col)] : b1[(((row / 64u) * 64u + (row % 64u) - 32u) * cols + col)]);
    const float v2 = b2[(row % 64u) * cols + col];
    const float v3 = b3[(row % 64u) * cols + col];
    float r0 = v0 * v2;
    float r1 = v1 * v3;
    float r2 = r0 + r1;
    bout[i] = r2;
}
